### ISSUE TITLE
please make config for minimal size and maximal size

### ISSUE THREAD

**Issue by matyklug18** [the-realest-stu/Lilliputian#14] opened 2018-01-10 00:14 UTC
it is annoing to have limitation. like littletiles. you can have smallest block even 1/16384 of block

**Comment by PenguinOwl** [comment] 2018-02-02 20:17
I’ve heard the mechanics and rendering get pretty wonky in large and small scales.

**Comment by cadaverous-eris** [comment] 2018-02-09 09:53
Duplicate of #4

**Closed as completed by cadaverous-eris** 2018-02-09 09:53 UTC
